version: "3.7"

x-app-config: &app-config
  MIX_ENV: test
  SECRET_KEY_BASE: secret_key
  GITHUB_EVENT_PATH: ${GITHUB_EVENT_PATH}
  GITHUB_TOKEN: ${GITHUB_TOKEN}

x-db-config: &db-config
  DATABASE_NAME: postgres
  DATABASE_USER: postgres
  DATABASE_PASSWORD: pgpassword
  DATABASE_HOST: db
  DATABASE_PORT: 5432
  POSTGRES_PASSWORD: pgpassword

services:
  api:
    image: userapp_api
    build:
      context: .
      args:
        ENV: test
    environment:
      <<: *app-config
      <<: *db-config
    depends_on:
      - db
    ports:
      - "4000:4000"
    stdin_open: true
    tty: true
    volumes:
      - /home/runner/work/_temp/_github_workflow:/home/runner/work/_temp/_github_workflow

  db:
    image: postgres:12.5-alpine
    environment: *db-config
    logging:
      driver: none
    ports:
      - "5432:5432"

volumes:
  sqlvolume: