name: Main

on:
  pull_request:
    branches:
      - 'develop'
  push:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        env:
          COVERAGE: true
          MIX_ENV: test
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
        run: docker-compose --file docker-compose.ci.yml run --rm api mix coveralls.github

      - name: Publish to coveralls.io
        uses: coverallsapp/github-action@v2.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
